#! /bin/bash
# author: Antonio Cervone <ant.cervone@gmail.com>
# modified by Nur Fadel <nuraiman@gmail.com>
# last update: 16-04-2012

HDF_SRC_DIR=/home/matteo/Documenti/PACS/lifev-env/hdf5-1.8.10-patch1

mkdir -p ${LIFEV_BUILD_DIR}
cd ${LIFEV_BUILD_DIR}
rm -f CMakeCache.txt
cmake \
  -D CMAKE_CXX_COMPILER:PATH="/usr/bin/mpicxx" \
  -D CMAKE_C_COMPILER:PATH="/usr/bin/mpicc" \
  -D CMAKE_INSTALL_PREFIX:PATH="/home/matteo/Documenti/PACS/lifev-env/hdf5-install" \
  -D HDF5_ENABLE_PARALLEL:BOOL=ON \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  $* \
  $HDF_SRC_DIR || return 1

#     -D BUILD_SHARED_LIBS:BOOL=TRUE \
